// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler_models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testContacts(t *testing.T) {
	t.Parallel()

	query := Contacts()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testContactsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContactsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Contacts().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContactsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ContactSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testContactsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ContactExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Contact exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ContactExists to return true, but got false.")
	}
}

func testContactsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	contactFound, err := FindContact(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if contactFound == nil {
		t.Error("want a record, got nil")
	}
}

func testContactsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Contacts().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testContactsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Contacts().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testContactsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	contactOne := &Contact{}
	contactTwo := &Contact{}
	if err = randomize.Struct(seed, contactOne, contactDBTypes, false, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}
	if err = randomize.Struct(seed, contactTwo, contactDBTypes, false, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = contactOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = contactTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Contacts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testContactsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	contactOne := &Contact{}
	contactTwo := &Contact{}
	if err = randomize.Struct(seed, contactOne, contactDBTypes, false, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}
	if err = randomize.Struct(seed, contactTwo, contactDBTypes, false, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = contactOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = contactTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func contactBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func contactAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Contact) error {
	*o = Contact{}
	return nil
}

func testContactsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Contact{}
	o := &Contact{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, contactDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Contact object: %s", err)
	}

	AddContactHook(boil.BeforeInsertHook, contactBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	contactBeforeInsertHooks = []ContactHook{}

	AddContactHook(boil.AfterInsertHook, contactAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	contactAfterInsertHooks = []ContactHook{}

	AddContactHook(boil.AfterSelectHook, contactAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	contactAfterSelectHooks = []ContactHook{}

	AddContactHook(boil.BeforeUpdateHook, contactBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	contactBeforeUpdateHooks = []ContactHook{}

	AddContactHook(boil.AfterUpdateHook, contactAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	contactAfterUpdateHooks = []ContactHook{}

	AddContactHook(boil.BeforeDeleteHook, contactBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	contactBeforeDeleteHooks = []ContactHook{}

	AddContactHook(boil.AfterDeleteHook, contactAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	contactAfterDeleteHooks = []ContactHook{}

	AddContactHook(boil.BeforeUpsertHook, contactBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	contactBeforeUpsertHooks = []ContactHook{}

	AddContactHook(boil.AfterUpsertHook, contactAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	contactAfterUpsertHooks = []ContactHook{}
}

func testContactsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testContactsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(contactColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testContactToManyPhoneNumbers(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Contact
	var b, c PhoneNumber

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, phoneNumberDBTypes, false, phoneNumberColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, phoneNumberDBTypes, false, phoneNumberColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.ContactID, a.ID)
	queries.Assign(&c.ContactID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.PhoneNumbers().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.ContactID, b.ContactID) {
			bFound = true
		}
		if queries.Equal(v.ContactID, c.ContactID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ContactSlice{&a}
	if err = a.L.LoadPhoneNumbers(ctx, tx, false, (*[]*Contact)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.PhoneNumbers); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.PhoneNumbers = nil
	if err = a.L.LoadPhoneNumbers(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.PhoneNumbers); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testContactToManyAddOpPhoneNumbers(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Contact
	var b, c, d, e PhoneNumber

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contactDBTypes, false, strmangle.SetComplement(contactPrimaryKeyColumns, contactColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PhoneNumber{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, phoneNumberDBTypes, false, strmangle.SetComplement(phoneNumberPrimaryKeyColumns, phoneNumberColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*PhoneNumber{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddPhoneNumbers(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.ContactID) {
			t.Error("foreign key was wrong value", a.ID, first.ContactID)
		}
		if !queries.Equal(a.ID, second.ContactID) {
			t.Error("foreign key was wrong value", a.ID, second.ContactID)
		}

		if first.R.Contact != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Contact != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.PhoneNumbers[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.PhoneNumbers[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.PhoneNumbers().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testContactToManySetOpPhoneNumbers(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Contact
	var b, c, d, e PhoneNumber

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contactDBTypes, false, strmangle.SetComplement(contactPrimaryKeyColumns, contactColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PhoneNumber{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, phoneNumberDBTypes, false, strmangle.SetComplement(phoneNumberPrimaryKeyColumns, phoneNumberColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetPhoneNumbers(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.PhoneNumbers().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetPhoneNumbers(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.PhoneNumbers().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.ContactID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.ContactID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.ContactID) {
		t.Error("foreign key was wrong value", a.ID, d.ContactID)
	}
	if !queries.Equal(a.ID, e.ContactID) {
		t.Error("foreign key was wrong value", a.ID, e.ContactID)
	}

	if b.R.Contact != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Contact != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Contact != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Contact != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.PhoneNumbers[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.PhoneNumbers[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testContactToManyRemoveOpPhoneNumbers(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Contact
	var b, c, d, e PhoneNumber

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, contactDBTypes, false, strmangle.SetComplement(contactPrimaryKeyColumns, contactColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PhoneNumber{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, phoneNumberDBTypes, false, strmangle.SetComplement(phoneNumberPrimaryKeyColumns, phoneNumberColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddPhoneNumbers(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.PhoneNumbers().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemovePhoneNumbers(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.PhoneNumbers().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.ContactID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.ContactID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Contact != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Contact != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Contact != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Contact != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.PhoneNumbers) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.PhoneNumbers[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.PhoneNumbers[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testContactsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testContactsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ContactSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testContactsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Contacts().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	contactDBTypes = map[string]string{`ID`: `integer`, `Name`: `character varying`}
	_              = bytes.MinRead
)

func testContactsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(contactPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(contactAllColumns) == len(contactPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, contactDBTypes, true, contactPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testContactsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(contactAllColumns) == len(contactPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Contact{}
	if err = randomize.Struct(seed, o, contactDBTypes, true, contactColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, contactDBTypes, true, contactPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(contactAllColumns, contactPrimaryKeyColumns) {
		fields = contactAllColumns
	} else {
		fields = strmangle.SetComplement(
			contactAllColumns,
			contactPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ContactSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testContactsUpsert(t *testing.T) {
	t.Parallel()

	if len(contactAllColumns) == len(contactPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Contact{}
	if err = randomize.Struct(seed, &o, contactDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Contact: %s", err)
	}

	count, err := Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, contactDBTypes, false, contactPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Contact struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Contact: %s", err)
	}

	count, err = Contacts().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
